name: Upload YouTube Video

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Create token.json
        run: |
          echo '${{ secrets.YT_TOKEN_JSON }}' > token.json

      - name: Create client_secret.json
        run: |
          echo '${{ secrets.YT_CLIENT_SECRET_JSON }}' > client_secret.json

      - name: Install deps
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 PyDrive

      - name: Debug (IMPORTANT)
        run: |
          echo "TOKEN SIZE:"
          wc -c token.json
          echo "CLIENT SIZE:"
          wc -c client_secret.json

      - name: Run script
        run: python upload_drive.py
